name: Mobile CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm install

  prettier:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v3
      - run: npm install
          npm run prettier

  lint:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm run lint

  build:
    runs-on: ubuntu-latest
    needs: [prettier, lint]
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm run prettier
      - run: npm run lint
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
