name: Mobile CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm install

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
